# -*- coding: utf-8 -*-
"""cronograma_auto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EjQTc4cLfaRrHgUDCehro7K7plyOhAbG
"""

# cronograma_auto.py
import pandas as pd

def gerar_cronograma_automatico(carga_horaria):
    """
    Gera cronograma automático baseado na carga horária
    - 34h: 1 atividade por semana (17 semanas)
    - 68h: 2 atividades por semana (34 linhas)
    - 102h: 3 atividades por semana (51 linhas)
    - 51h e 85h: retorna None (preenchimento manual)
    """

    if not carga_horaria:
        return None

    # Converte para inteiro, tratando string vazia
    try:
        carga = int(carga_horaria)
    except:
        return None

    # Modelos pré-definidos
    if carga == 34:
        # 1 atividade por semana
        dados = []
        for semana in range(1, 18):
            dados.append({
                "Semana": str(semana),
                "Data": "",
                "Duração": "2 h",
                "Conteúdo": f"Atividade {semana}",
                "Estratégia Didática": "",
                "Avaliação": ""
            })
        # Adicionar prova final
        dados.append({
            "Semana": "17",
            "Data": "",
            "Duração": "2 h",
            "Conteúdo": "Prova Final",
            "Estratégia Didática": "Avaliação Escrita",
            "Avaliação": "Prova"
        })
        return pd.DataFrame(dados)

    elif carga == 68:
        # 2 atividades por semana
        dados = []
        for semana in range(1, 18):
            for atividade in range(1, 3):  # 2 atividades por semana
                dados.append({
                    "Semana": str(semana),
                    "Data": "",
                    "Duração": "2 h",
                    "Conteúdo": f"Atividade {semana}.{atividade}",
                    "Estratégia Didática": "",
                    "Avaliação": ""
                })
        # Adicionar prova final
        dados.append({
            "Semana": "17",
            "Data": "",
            "Duração": "2 h",
            "Conteúdo": "Prova Final",
            "Estratégia Didática": "Avaliação Escrita",
            "Avaliação": "Prova"
        })
        return pd.DataFrame(dados)

    elif carga == 102:
        # 3 atividades por semana
        dados = []
        for semana in range(1, 18):
            for atividade in range(1, 4):  # 3 atividades por semana
                dados.append({
                    "Semana": str(semana),
                    "Data": "",
                    "Duração": "2 h",
                    "Conteúdo": f"Atividade {semana}.{atividade}",
                    "Estratégia Didática": "",
                    "Avaliação": ""
                })
        # Adicionar prova final
        dados.append({
            "Semana": "17",
            "Data": "",
            "Duração": "2 h",
            "Conteúdo": "Prova Final",
            "Estratégia Didática": "Avaliação Escrita",
            "Avaliação": "Prova"
        })
        return pd.DataFrame(dados)

    else:  # 51 e 85 retornam None
        return None

def get_cargas_com_auto():
    """Retorna lista de cargas que têm geração automática"""
    return [34, 68, 102]

def get_descricao_carga(carga):
    """Retorna descrição amigável da carga horária"""
    try:
        carga_int = int(carga) if carga else 0
    except:
        carga_int = 0

    descricoes = {
        34: "1 atividade por semana (17 aulas + prova final)",
        51: "Preenchimento manual",
        68: "2 atividades por semana (34 aulas + prova final)",
        85: "Preenchimento manual",
        102: "3 atividades por semana (51 aulas + prova final)"
    }
    return descricoes.get(carga_int, "")